# Generated by Django 4.2.23 on 2025-08-04 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('civ_intel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Select the state where the incident occurred', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='civ_intel.state'),
        ),
    ]
