# Generated by Django 4.2.23 on 2025-08-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civ_intel', '0003_alter_report_location_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name'], 'verbose_name_plural': 'States'},
        ),
        migrations.AddField(
            model_name='state',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
